/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-05 01:46:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/usr/local/apache-tomcat-8.5.50-1/webapps/session/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583155514000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String path = request.getContextPath();

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>简历表</title>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        $(function () {\n");
      out.write("\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function add() {\n");
      out.write("            $(\"#id\").val(\"\");\n");
      out.write("            $(\"#name\").val(\"\");\n");
      out.write("            $(\"#address\").val(\"\");\n");
      out.write("            $(\"#phone\").val(\"\");\n");
      out.write("            popBox();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function update(id, name, address, phone) {\n");
      out.write("            $(\"#id\").val(id);\n");
      out.write("            $(\"#name\").val(name);\n");
      out.write("            $(\"#address\").val(address);\n");
      out.write("            $(\"#phone\").val(phone);\n");
      out.write("            popBox();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*点击弹出按钮*/\n");
      out.write("        function popBox() {\n");
      out.write("            var popBox = document.getElementById(\"popBox\");\n");
      out.write("            var popLayer = document.getElementById(\"popLayer\");\n");
      out.write("            popBox.style.display = \"block\";\n");
      out.write("            popLayer.style.display = \"block\";\n");
      out.write("\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        /*点击关闭按钮*/\n");
      out.write("        function closeBox() {\n");
      out.write("            var popBox = document.getElementById(\"popBox\");\n");
      out.write("            var popLayer = document.getElementById(\"popLayer\");\n");
      out.write("            popBox.style.display = \"none\";\n");
      out.write("            popLayer.style.display = \"none\";\n");
      out.write("\n");
      out.write("            $(\"#id\").val(\"\");\n");
      out.write("            $(\"#name\").val(\"\");\n");
      out.write("            $(\"#address\").val(\"\");\n");
      out.write("            $(\"#phone\").val(\"\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function deleteResume(id) {\n");
      out.write("            $.ajax({\n");
      out.write("                url: '");
      out.print(path);
      out.write("/resume/' + id,\n");
      out.write("                type: 'DELETE',\n");
      out.write("                contentType: 'application/json;charset=utf-8',\n");
      out.write("                success: function (data) {\n");
      out.write("                    if (data == \"success\") {\n");
      out.write("                        alert(\"删除成功\");\n");
      out.write("                        window.location.reload();\n");
      out.write("                    } else {\n");
      out.write("                        alert(\"删除失败\");\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function (XMLHttpRequest, textStatus, errorThrown) {\n");
      out.write("                    // $(\"#p_test\").innerHTML = \"there is something wrong!\";\n");
      out.write("                    alert(XMLHttpRequest.status);\n");
      out.write("                    alert(XMLHttpRequest.readyState);\n");
      out.write("                    alert(textStatus);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function submit() {\n");
      out.write("            var id = $(\"#id\").val();\n");
      out.write("            var name = $(\"#name\").val();\n");
      out.write("            var address = $(\"#address\").val();\n");
      out.write("            var phone = $(\"#phone\").val();\n");
      out.write("\n");
      out.write("            if(id == undefined || id == null || id == ''){\n");
      out.write("                insertResume(name, address, phone);\n");
      out.write("            } else {\n");
      out.write("                updateResume(id, name, address, phone);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function updateResume(id, name, address, phone) {\n");
      out.write("            $.ajax({\n");
      out.write("                url: '");
      out.print(path);
      out.write("/resume/' + id + '/' + name + '/' + address + '/' + phone,\n");
      out.write("                type: 'PUT',\n");
      out.write("                contentType: 'application/json;charset=utf-8',\n");
      out.write("                success: function (data) {\n");
      out.write("                    closeBox();\n");
      out.write("                    if (data == \"success\") {\n");
      out.write("                        alert(\"更新成功\");\n");
      out.write("                        window.location.reload();\n");
      out.write("                    } else {\n");
      out.write("                        alert(\"更新失败\");\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function (XMLHttpRequest, textStatus, errorThrown) {\n");
      out.write("                    // $(\"#p_test\").innerHTML = \"there is something wrong!\";\n");
      out.write("                    alert(XMLHttpRequest.status);\n");
      out.write("                    alert(XMLHttpRequest.readyState);\n");
      out.write("                    alert(textStatus);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function insertResume(name, address, phone) {\n");
      out.write("            $.ajax({\n");
      out.write("                url: '");
      out.print(path);
      out.write("/resume/' + name + '/' + address + '/' + phone,\n");
      out.write("                type: 'GET',\n");
      out.write("                contentType: 'application/json;charset=utf-8',\n");
      out.write("                success: function (data) {\n");
      out.write("                    closeBox();\n");
      out.write("                    if (data == \"success\") {\n");
      out.write("                        alert(\"添加成功\");\n");
      out.write("                        window.location.reload();\n");
      out.write("                    } else {\n");
      out.write("                        alert(\"添加失败\");\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function (XMLHttpRequest, textStatus, errorThrown) {\n");
      out.write("                    // $(\"#p_test\").innerHTML = \"there is something wrong!\";\n");
      out.write("                    alert(XMLHttpRequest.status);\n");
      out.write("                    alert(XMLHttpRequest.readyState);\n");
      out.write("                    alert(textStatus);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            padding:10px 10px 0 10px;\n");
      out.write("        }\n");
      out.write("        table{\n");
      out.write("            border-right:1px solid #000;\n");
      out.write("            border-bottom:1px solid #000\n");
      out.write("        }\n");
      out.write("        table td, table th{\n");
      out.write("            border-left:1px solid #000;\n");
      out.write("            border-top:1px solid #000;\n");
      out.write("            padding: 5px 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*背景层*/\n");
      out.write("        #popLayer {\n");
      out.write("            display: none;\n");
      out.write("            background-color: #B3B3B3;\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            left: 0;\n");
      out.write("            z-index: 10;\n");
      out.write("            -moz-opacity: 0.8;\n");
      out.write("            opacity:.80;\n");
      out.write("            filter: alpha(opacity=80);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*弹出层*/\n");
      out.write("        #popBox {\n");
      out.write("            display: none;\n");
      out.write("            background-color: #FFFFFF;\n");
      out.write("            z-index: 11;\n");
      out.write("            width: 200px;\n");
      out.write("            height: 200px;\n");
      out.write("            position:fixed;\n");
      out.write("            top:0;\n");
      out.write("            right:0;\n");
      out.write("            left:0;\n");
      out.write("            bottom:0;\n");
      out.write("            margin:auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #popBox .close{\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*关闭按钮*/\n");
      out.write("        #popBox .close a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #2D2C3B;\n");
      out.write("        }\n");
      out.write("        input[type=\"button\"]{\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin: 5px 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div style=\"text-align: right\">\n");
      out.write("        <a href=\"");
      out.print(path);
      out.write("/logout\">退出</a>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("        <input type=\"button\" name=\"popBox\" value=\"新增\" onclick=\"popBox()\">\n");
      out.write("        <div id=\"popLayer\"></div>\n");
      out.write("        <div id=\"popBox\">\n");
      out.write("            <div class=\"content\">\n");
      out.write("                <span>姓名：<input type=\"text\" id=\"name\"></span>\n");
      out.write("                <span>地址：<input type=\"text\" id=\"address\"></span>\n");
      out.write("                <span>电话：<input type=\"text\" id=\"phone\"></span>\n");
      out.write("                <input type=\"hidden\" id=\"id\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"close\">\n");
      out.write("                <input type=\"button\" value=\"关闭\" onclick=\"closeBox()\">\n");
      out.write("                <input type=\"button\" value=\"确定\" onclick=\"submit()\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("            <tr>\n");
      out.write("                <th >id</th>\n");
      out.write("                <th>姓名</th>\n");
      out.write("                <th>地址</th>\n");
      out.write("                <th>手机</th>\n");
      out.write("                <th>操作</th>\n");
      out.write("            </tr>\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/list.jsp(229,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/list.jsp(229,12) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/list.jsp(229,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/jsp/list.jsp(229,12) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                <tr>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                    <td>\n");
            out.write("                        <input type=\"button\" value=\"编辑\"\n");
            out.write("                               onclick=\"update(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">\n");
            out.write("                        <input type=\"button\" value=\"删除\" onclick=\"deleteResume(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">\n");
            out.write("                    </td>\n");
            out.write("                </tr>\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
